import {defineApp,feature} from './domain-config.mjs';
export default defineApp({
  "id": "ai-coop-advertising-mdf-recovery",
  "engine": "recovery",
  "title": "Co-op Advertising & Market Development Fund Recovery",
  "shortTitle": "MDF Recovery OS",
  "tagline": "Calculate earned partner funds, assemble compliant proof, submit claims, and prevent expiration",
  "industry": "Channel Marketing Financial Operations",
  "uiPort": 4588,
  "apiPort": 5588,
  "accent": "#7e22ce",
  "currency": "USD",
  "primaryOutcome": "Earned co-op and market-development funds converted into approved claims and collected cash",
  "valueNarrative": "Connect program rules, partner sales, accruals, campaigns, preapprovals, invoices, proof of performance, claims, rejections, and payments.",
  "calculation": {
    "actualKey": "paidFunds",
    "expectedKey": "earnedFunds",
    "actualLabel": "Approved & Paid Funds",
    "expectedLabel": "Calculated Earned Funds",
    "varianceLabel": "Unrecovered supported value",
    "direction": "expected-minus-actual",
    "finding": "Program accrual, partner activity, campaign, and proof evidence indicate unclaimed or unpaid channel marketing funds.",
    "actions": [
      "Validate the governing agreement and effective rules",
      "Reconcile transaction-level source evidence",
      "Prepare and submit the recovery or correction package",
      "Track response and reconcile realized financial outcome"
    ]
  }
},[
feature("program-and-agreement-library","MRO01","Program and agreement library","Reconcile program and agreement library using co-op and MDF agreements, partner records, sales accruals, campaign plans, preapprovals, invoices, payment proof, brand compliance, proof of performance, claims, rejections, and credits.","Produce a governed program and agreement library decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["programPartner","Program / Channel Partner","text","Nova Technology MDF / Reseller-184"],["caseReference","Program and agreement library Reference","text","MRO01-2026-001"],["paidFunds","Approved & Paid Funds","currency",486000],["earnedFunds","Calculated Earned Funds","currency",612500],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"paidFunds",subjects:["Technology reseller MDF","Automotive dealer co-op","Appliance retailer program","Industrial distributor campaign","Franchise marketing fund"]}),
feature("partner-and-dealer-registry","MRO02","Partner and dealer registry","Reconcile partner and dealer registry using co-op and MDF agreements, partner records, sales accruals, campaign plans, preapprovals, invoices, payment proof, brand compliance, proof of performance, claims, rejections, and credits.","Produce a governed partner and dealer registry decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["programPartner","Program / Channel Partner","text","Nova Technology MDF / Reseller-184"],["caseReference","Partner and dealer registry Reference","text","MRO02-2026-001"],["paidFunds","Approved & Paid Funds","currency",486000],["earnedFunds","Calculated Earned Funds","currency",612500],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"paidFunds",subjects:["Technology reseller MDF","Automotive dealer co-op","Appliance retailer program","Industrial distributor campaign","Franchise marketing fund"]}),
feature("fund-accrual-calculation","MRO03","Fund accrual calculation","Reconcile fund accrual calculation using co-op and MDF agreements, partner records, sales accruals, campaign plans, preapprovals, invoices, payment proof, brand compliance, proof of performance, claims, rejections, and credits.","Produce a governed fund accrual calculation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["programPartner","Program / Channel Partner","text","Nova Technology MDF / Reseller-184"],["caseReference","Fund accrual calculation Reference","text","MRO03-2026-001"],["paidFunds","Approved & Paid Funds","currency",486000],["earnedFunds","Calculated Earned Funds","currency",612500],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"paidFunds",subjects:["Technology reseller MDF","Automotive dealer co-op","Appliance retailer program","Industrial distributor campaign","Franchise marketing fund"]}),
feature("eligibility-and-activity-rules","MRO04","Eligibility and activity rules","Reconcile eligibility and activity rules using co-op and MDF agreements, partner records, sales accruals, campaign plans, preapprovals, invoices, payment proof, brand compliance, proof of performance, claims, rejections, and credits.","Produce a governed eligibility and activity rules decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["programPartner","Program / Channel Partner","text","Nova Technology MDF / Reseller-184"],["caseReference","Eligibility and activity rules Reference","text","MRO04-2026-001"],["paidFunds","Approved & Paid Funds","currency",486000],["earnedFunds","Calculated Earned Funds","currency",612500],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"paidFunds",subjects:["Technology reseller MDF","Automotive dealer co-op","Appliance retailer program","Industrial distributor campaign","Franchise marketing fund"]}),
feature("campaign-preapproval","MRO05","Campaign preapproval","Reconcile campaign preapproval using co-op and MDF agreements, partner records, sales accruals, campaign plans, preapprovals, invoices, payment proof, brand compliance, proof of performance, claims, rejections, and credits.","Produce a governed campaign preapproval decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["programPartner","Program / Channel Partner","text","Nova Technology MDF / Reseller-184"],["caseReference","Campaign preapproval Reference","text","MRO05-2026-001"],["paidFunds","Approved & Paid Funds","currency",486000],["earnedFunds","Calculated Earned Funds","currency",612500],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"paidFunds",subjects:["Technology reseller MDF","Automotive dealer co-op","Appliance retailer program","Industrial distributor campaign","Franchise marketing fund"]}),
feature("proof-of-performance-collection","MRO06","Proof-of-performance collection","Reconcile proof-of-performance collection using co-op and MDF agreements, partner records, sales accruals, campaign plans, preapprovals, invoices, payment proof, brand compliance, proof of performance, claims, rejections, and credits.","Produce a governed proof-of-performance collection decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["programPartner","Program / Channel Partner","text","Nova Technology MDF / Reseller-184"],["caseReference","Proof-of-performance collection Reference","text","MRO06-2026-001"],["paidFunds","Approved & Paid Funds","currency",486000],["earnedFunds","Calculated Earned Funds","currency",612500],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"paidFunds",subjects:["Technology reseller MDF","Automotive dealer co-op","Appliance retailer program","Industrial distributor campaign","Franchise marketing fund"]}),
feature("invoice-and-payment-evidence","MRO07","Invoice and payment evidence","Reconcile invoice and payment evidence using co-op and MDF agreements, partner records, sales accruals, campaign plans, preapprovals, invoices, payment proof, brand compliance, proof of performance, claims, rejections, and credits.","Produce a governed invoice and payment evidence decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["programPartner","Program / Channel Partner","text","Nova Technology MDF / Reseller-184"],["caseReference","Invoice and payment evidence Reference","text","MRO07-2026-001"],["paidFunds","Approved & Paid Funds","currency",486000],["earnedFunds","Calculated Earned Funds","currency",612500],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"paidFunds",subjects:["Technology reseller MDF","Automotive dealer co-op","Appliance retailer program","Industrial distributor campaign","Franchise marketing fund"]}),
feature("brand-compliance-validation","MRO08","Brand compliance validation","Reconcile brand compliance validation using co-op and MDF agreements, partner records, sales accruals, campaign plans, preapprovals, invoices, payment proof, brand compliance, proof of performance, claims, rejections, and credits.","Produce a governed brand compliance validation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["programPartner","Program / Channel Partner","text","Nova Technology MDF / Reseller-184"],["caseReference","Brand compliance validation Reference","text","MRO08-2026-001"],["paidFunds","Approved & Paid Funds","currency",486000],["earnedFunds","Calculated Earned Funds","currency",612500],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"paidFunds",subjects:["Technology reseller MDF","Automotive dealer co-op","Appliance retailer program","Industrial distributor campaign","Franchise marketing fund"]}),
feature("claim-deadline-tracking","MRO09","Claim deadline tracking","Reconcile claim deadline tracking using co-op and MDF agreements, partner records, sales accruals, campaign plans, preapprovals, invoices, payment proof, brand compliance, proof of performance, claims, rejections, and credits.","Produce a governed claim deadline tracking decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["programPartner","Program / Channel Partner","text","Nova Technology MDF / Reseller-184"],["caseReference","Claim deadline tracking Reference","text","MRO09-2026-001"],["paidFunds","Approved & Paid Funds","currency",486000],["earnedFunds","Calculated Earned Funds","currency",612500],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"paidFunds",subjects:["Technology reseller MDF","Automotive dealer co-op","Appliance retailer program","Industrial distributor campaign","Franchise marketing fund"]}),
feature("claim-preparation-and-submission","MRO10","Claim preparation and submission","Reconcile claim preparation and submission using co-op and MDF agreements, partner records, sales accruals, campaign plans, preapprovals, invoices, payment proof, brand compliance, proof of performance, claims, rejections, and credits.","Produce a governed claim preparation and submission decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["programPartner","Program / Channel Partner","text","Nova Technology MDF / Reseller-184"],["caseReference","Claim preparation and submission Reference","text","MRO10-2026-001"],["paidFunds","Approved & Paid Funds","currency",486000],["earnedFunds","Calculated Earned Funds","currency",612500],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"paidFunds",subjects:["Technology reseller MDF","Automotive dealer co-op","Appliance retailer program","Industrial distributor campaign","Franchise marketing fund"]}),
feature("vendor-rejection-management","MRO11","Vendor rejection management","Reconcile vendor rejection management using co-op and MDF agreements, partner records, sales accruals, campaign plans, preapprovals, invoices, payment proof, brand compliance, proof of performance, claims, rejections, and credits.","Produce a governed vendor rejection management decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["programPartner","Program / Channel Partner","text","Nova Technology MDF / Reseller-184"],["caseReference","Vendor rejection management Reference","text","MRO11-2026-001"],["paidFunds","Approved & Paid Funds","currency",486000],["earnedFunds","Calculated Earned Funds","currency",612500],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"paidFunds",subjects:["Technology reseller MDF","Automotive dealer co-op","Appliance retailer program","Industrial distributor campaign","Franchise marketing fund"]}),
feature("resubmission-workflow","MRO12","Resubmission workflow","Reconcile resubmission workflow using co-op and MDF agreements, partner records, sales accruals, campaign plans, preapprovals, invoices, payment proof, brand compliance, proof of performance, claims, rejections, and credits.","Produce a governed resubmission workflow decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["programPartner","Program / Channel Partner","text","Nova Technology MDF / Reseller-184"],["caseReference","Resubmission workflow Reference","text","MRO12-2026-001"],["paidFunds","Approved & Paid Funds","currency",486000],["earnedFunds","Calculated Earned Funds","currency",612500],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"paidFunds",subjects:["Technology reseller MDF","Automotive dealer co-op","Appliance retailer program","Industrial distributor campaign","Franchise marketing fund"]}),
feature("credit-and-payment-reconciliation","MRO13","Credit and payment reconciliation","Reconcile credit and payment reconciliation using co-op and MDF agreements, partner records, sales accruals, campaign plans, preapprovals, invoices, payment proof, brand compliance, proof of performance, claims, rejections, and credits.","Produce a governed credit and payment reconciliation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["programPartner","Program / Channel Partner","text","Nova Technology MDF / Reseller-184"],["caseReference","Credit and payment reconciliation Reference","text","MRO13-2026-001"],["paidFunds","Approved & Paid Funds","currency",486000],["earnedFunds","Calculated Earned Funds","currency",612500],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"paidFunds",subjects:["Technology reseller MDF","Automotive dealer co-op","Appliance retailer program","Industrial distributor campaign","Franchise marketing fund"]}),
feature("expiring-fund-alerts","MRO14","Expiring-fund alerts","Reconcile expiring-fund alerts using co-op and MDF agreements, partner records, sales accruals, campaign plans, preapprovals, invoices, payment proof, brand compliance, proof of performance, claims, rejections, and credits.","Produce a governed expiring-fund alerts decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["programPartner","Program / Channel Partner","text","Nova Technology MDF / Reseller-184"],["caseReference","Expiring-fund alerts Reference","text","MRO14-2026-001"],["paidFunds","Approved & Paid Funds","currency",486000],["earnedFunds","Calculated Earned Funds","currency",612500],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"paidFunds",subjects:["Technology reseller MDF","Automotive dealer co-op","Appliance retailer program","Industrial distributor campaign","Franchise marketing fund"]}),
feature("partner-utilization-analytics","MRO15","Partner utilization analytics","Reconcile partner utilization analytics using co-op and MDF agreements, partner records, sales accruals, campaign plans, preapprovals, invoices, payment proof, brand compliance, proof of performance, claims, rejections, and credits.","Produce a governed partner utilization analytics decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["programPartner","Program / Channel Partner","text","Nova Technology MDF / Reseller-184"],["caseReference","Partner utilization analytics Reference","text","MRO15-2026-001"],["paidFunds","Approved & Paid Funds","currency",486000],["earnedFunds","Calculated Earned Funds","currency",612500],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"paidFunds",subjects:["Technology reseller MDF","Automotive dealer co-op","Appliance retailer program","Industrial distributor campaign","Franchise marketing fund"]}),
feature("campaign-roi-and-recovery-analytics","MRO16","Campaign ROI and recovery analytics","Reconcile campaign roi and recovery analytics using co-op and MDF agreements, partner records, sales accruals, campaign plans, preapprovals, invoices, payment proof, brand compliance, proof of performance, claims, rejections, and credits.","Produce a governed campaign roi and recovery analytics decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["programPartner","Program / Channel Partner","text","Nova Technology MDF / Reseller-184"],["caseReference","Campaign ROI and recovery analytics Reference","text","MRO16-2026-001"],["paidFunds","Approved & Paid Funds","currency",486000],["earnedFunds","Calculated Earned Funds","currency",612500],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"paidFunds",subjects:["Technology reseller MDF","Automotive dealer co-op","Appliance retailer program","Industrial distributor campaign","Franchise marketing fund"]})
]);
